<?php //Http definition of user form showing a table of users data ?>

<a href="/users/insert">Insert</a>
<table class="table table-striped">
<?php foreach ($data as $key => $fila):?>
    <tr>
        <?php 
        $columna = explode("|", $fila);       
        foreach ($columna as $value):?>
            <td><?=$value;?></td>
        <?php endforeach;?>
        <td>
            <a href="/users/update/id/<?=$columna[0];?>">Update</a> | 
            <a href="/users/delete/id/<?=$columna[0];?>">Delete</a>
        </td>
   </tr>
<?php endforeach;?>
</table>
