<?php 

echo "<a href=\"users.php?action=insert\">Insert</a>";

echo "<table border=1>";
foreach ($data as $key => $fila)
{
    echo "<tr>";
    $columna = explode("|", $fila);
    foreach ($columna as $value)
    {
        echo "<td>".$value."</td>";
    }

    echo "<td>";
    echo "<a href=\"users.php?action=update&id=".$key."\">Update</a> | ";
    echo "<a href=\"users.php?action=delete&id=".$key."\">Delete</a>";
    echo "</td>";
    echo "</tr>";
}

echo "</table>";